// @/hooks/useVisibleContainers.ts
import { useMemo } from 'react'
import { Container, StopStatus, RouteStop } from '@/constants/types'

/**
 * Builds a composite key for matching containers to delivery operations.
 */
function containerDeliveryKey(
	contractIndex: number,
	deliveryPointIndex: number,
): string {
	return `${contractIndex}:${deliveryPointIndex}`
}

/**
 * Determines which containers should be visible on the cargo grid based on
 * the current stop statuses from the route checklist.
 *
 * Visibility rules:
 *
 * 1. **Pickup gating** — A container only appears on the grid when the stop
 *    at which it is picked up has been set to "in-progress" or "completed".
 *    This means the user is currently at (or has already visited) the pickup
 *    location and the cargo is being (or has been) loaded.
 *
 * 2. **Delivery removal** — A container is removed from the grid when the
 *    stop at which it is delivered has been marked "completed". This means
 *    the user has finished unloading at that delivery location.
 *
 * Containers without a `pickupLocation` (edge case) are always visible
 * unless removed by a completed delivery.
 *
 * If no route stops exist (no route generated), all containers are shown
 * so the basic layout view still works without the checklist.
 *
 * @param containers  - All containers generated by the layout engine
 * @param stopStatuses - Current status of each route stop (keyed by location)
 * @param stops       - The route stops with pickup and delivery operation data
 * @returns The filtered list of containers that should render on the grid
 */
export function useVisibleContainers(
	containers: Container[],
	stopStatuses: Record<string, StopStatus>,
	stops: RouteStop[],
): Container[] {
	// Build a set of locations that have pickup operations
	const pickupLocations = useMemo(() => {
		const locations = new Set<string>()
		for (const stop of stops) {
			if (stop.type === 'pickup' || stop.type === 'both') {
				locations.add(stop.location)
			}
		}
		return locations
	}, [stops])

	// Build a set of container keys (contractIndex:deliveryIndex) that have
	// been fully delivered — i.e. the delivery stop is "completed".
	const deliveredContainerKeys = useMemo(() => {
		const keys = new Set<string>()
		for (const stop of stops) {
			// Only consider stops that have delivery operations
			if (stop.type !== 'delivery' && stop.type !== 'both') continue

			// Only remove containers when the stop is completed
			const status = stopStatuses[stop.location] || 'idle'
			if (status !== 'completed') continue

			for (const delivery of stop.operations.deliveries) {
				keys.add(
					containerDeliveryKey(
						delivery.contractIndex,
						delivery.deliveryPointIndex,
					),
				)
			}
		}
		return keys
	}, [stops, stopStatuses])

	return useMemo(() => {
		// If there are no stops at all (no route generated), show all containers
		// so the basic layout view still works without the checklist
		if (stops.length === 0) {
			return containers
		}

		return containers.filter((container) => {
			// ── Delivery removal check ──────────────────────────────────
			// If this container's delivery stop is completed, hide it
			// (it has been unloaded at the destination).
			const key = containerDeliveryKey(
				container.contractIndex,
				container.deliveryIndex,
			)
			if (deliveredContainerKeys.has(key)) {
				return false
			}

			// ── Pickup gating check ─────────────────────────────────────
			const pickup = container.pickupLocation

			// Containers without a pickup location are always visible
			if (!pickup) return true

			// If this pickup location isn't in our route stops as a pickup,
			// show it (defensive — shouldn't normally happen)
			if (!pickupLocations.has(pickup)) return true

			const status = stopStatuses[pickup] || 'idle'
			return status === 'in-progress' || status === 'completed'
		})
	}, [containers, stopStatuses, stops, pickupLocations, deliveredContainerKeys])
}
